baseURL = ""
languageCode = "fr-fr"
title = "KWEI 2021"
theme = "cactus"
disableKinds = ["taxonomyTerm"]

[markup]
  [markup.tableOfContents]
      endLevel = 4
      ordered = false
      startLevel = 2


[params]
  colortheme = "dark" # dark, light, white, or classic

  # Home page settings
  description = "Site internet du KWEI"

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "02/01/2006"

  [params.comments]
    enabled = false

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "BDL"
    link = "https://wiki.crans.org/VieBdl"
